### ISSUE TITLE
java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp"

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.java#572]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://10.47.65.249:20009"
java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://10.47.65.249:20009"
  at org.eclipse.paho.mqttv5.client.internal.NetworkModuleService.validateURI(NetworkModuleService.java:70)
  at org.eclipse.paho.mqttv5.client.MqttAsyncClient.<init>(MqttAsyncClient.java:582)
  at org.eclipse.paho.mqttv5.client.MqttAsyncClient.<init>(MqttAsyncClient.java:448)
  at com.ibm.ism.ws.test.MyConnection.<init>(MyConnection.java:168)
  at com.ibm.ism.ws.test.CreateConnectionAction.invokeApi(CreateConnectionAction.java:445)
  at com.ibm.ism.ws.test.ApiCallAction.run(ApiCallAction.java:159)
  at com.ibm.ism.ws.test.Action.execute(Action.java:256)
  at com.ibm.ism.ws.test.CompositeAction$CompositeActionRunable.run(CompositeAction.java:189)
  at java.lang.Thread.run(Thread.java:785)

[13/08/18 16:27:33:770 CDT] 000015 E ISMTEST1235: Action CreateConnectionQuiet1 failed. The reason is: null
java.util.NoSuchElementException
java.util.NoSuchElementException
  at java.net.URLClassLoader$2.nextElement(URLClassLoader.java:963)
  at java.net.URLClassLoader$2.nextElement(URLClassLoader.java:938)
  at java.lang.ClassLoader$CompoundEnumeration.nextElement(ClassLoader.java:593)
  at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:368)
  at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:404)
  at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:485)
  at org.eclipse.paho.mqttv5.client.internal.NetworkModuleService.validateURI(NetworkModuleService.java:64)
  at org.eclipse.paho.mqttv5.client.MqttAsyncClient.<init>(MqttAsyncClient.java:582)
  at org.eclipse.paho.mqttv5.client.MqttAsyncClient.<init>(MqttAsyncClient.java:448)
  at com.ibm.ism.ws.test.MyConnection.<init>(MyConnection.java:168)
  at com.ibm.ism.ws.test.CreateConnectionAction.invokeApi(CreateConnectionAction.java:445)
  at com.ibm.ism.ws.test.ApiCallAction.run(ApiCallAction.java:159)
  at com.ibm.ism.ws.test.Action.execute(Action.java:256)
  at com.ibm.ism.ws.test.CompositeAction$CompositeActionRunable.run(CompositeAction.java:189)
  at java.lang.Thread.run(Thread.java:785)

**Comment by icraggs** [comment]
I've added a fix - just synchronising access to NetworkModuleService.validateURI().  What changed since the merge of the 'new websocket header enhancement', I'm not sure.

**Comment by leetosc** [comment]
I'm still getting errors with the new version of the client.  Each run the set of exceptions thrown is different. 
```
Thread 12 is running
Thread 13 is running
Thread 11 is running
Thread 11: Exception..java.util.NoSuchElementException
Thread 13: Exception..java.util.NoSuchElementException
Thread 12: Exception..java.util.NoSuchElementException
Connect complete: tcp://9.3.179.54:16102
wildcard=true
Thread 10: connect: org.eclipse.paho.mqttv5.client.MqttToken@5b1509f2
Thread 10 Disconnecting
```
```
Thread 10 is running
Thread 13 is running
Thread 12 is running
Thread 11 is running
Thread 13: Exception..java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://9.3.179.54:16102"
Thread 10: Exception..java.util.NoSuchElementException
Thread 11: Exception..java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://9.3.179.54:16102"
Thread 12: Exception..java.util.NoSuchElementException
```

**Comment by icraggs** [comment]
I see connection errors, but not the "noSuchElementException"

**Comment by icraggs** [comment]
This fix is added to the develop branch only.  I don't see the 'no NetworkModule'  errors any more.  

In the supplied test program there are errors on starting > 5 client threads simultaneously, which is removed if there is a 50ms interval before the connect of each batch of 5 threads.  This apparently occurred with the previous version of the client too, so it should be nothing new.  I would like to get to the bottom of it however.

**Comment by leetosc** [comment]
Adding a delay between starting each thread helps somewhat - a few threads will connect successfully, however the errors still occur consistently (both the IllegalArgumentException and the NoSuchElementException) on the remaining threads.

This never occurred in the previous version of the clients, even with no delay between starting the threads.

**Comment by icraggs** [comment]
The fix I added to the develop branch works for me - I don't get any of these errors any more with the test program you supplied.  So we need to be sure that you're picking up the fix. 

@jpwsutton can we merge this to master?  How do we usually deliver these fixes.

**Comment by leetosc** [comment]
I pulled the latest versions and it does look like it's working now.  
`org.eclipse.paho.mqttv5.common-1.2.1-20180824.040636-54.jar`
`org.eclipse.paho.mqttv5.common-1.2.1-20180824.040636-54.jar`

**Comment by ddwang** [comment]
Looks like this problem is still happening with official v1.2.1 release on Maven

In particular access to `NetworkModuleService.validateURI()` does not appear to be synchronized, was that on a dev branch only?

**Comment by OliverNiedergriese** [comment]
I also have the problem with the v1.2.1 release.
Was the fix only submitted for mqttv5 or also for mqttv3?

**Comment by icraggs** [comment]
I added the fix only for V5 apparently.  I didn't add it to V3 because no one had reported it there.  If someone would like to open an issue for V3 (or a PR), I will add the fix to the next release.

**Comment by ghost** [comment]
Any further action?

**Comment by hbergmey** [comment]
Has this already been fixed for V3? I am seeing a similar error message with "wss" protocol.

**Comment by lucastaehli** [comment]
Same problem here with v1.2.1

**Comment by alex-makarov** [comment]
Same problem with v1.2.1 on V3, for "ssl" scheme. 1.2.0 works fine.

**Comment by derolf** [comment]
Version mqttv3-1.2.1: `Getting java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://localhost:1883"`.

**Comment by icraggs** [comment]
I've added the same fix as I did for MQTT V5 for V3 in the develop branch, 1.2.2-SNAPSHOT, which is available at repo.eclipse.org.

**Comment by JiriBilek** [comment]
I am fighting with this bug, too. I hoped that loading https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.2.2-SNAPSHOT/org.eclipse.paho.client.mqttv3-1.2.2-20190418.040541-4.jar will be ok, but I had to revert to https://repo.eclipse.org/content/repositories/paho/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.2.0/org.eclipse.paho.client.mqttv3-1.2.0.jar
Maybe I am doing something wrong, it's a long time since I wrote my last android app. I am not using maven, I just copy the library to the project _libs_ folder

**Comment by sp193** [comment]
I compiled a new build of the MQTT v3 clien, based on the develop branch, and have not seen this glitch appear ever again... Yet.

**Comment by mbaeuerle** [comment]
Thanks for fixing this problem! Is there a roadmap when version 1.2.2 will be released?

**Comment by veita** [comment]
We are experiencing this problem in production with the MQTTv3 1.2.1 release client library.

It can be reproduced with this two lines of code:
```java
  for (int i = 0; i < 50; i++) {
    new Thread(() -> NetworkModuleService.validateURI("ssl://mqtt.example.org:8883")).start();
  }
```
The root cause of this bug seems to be a race condition (in JDK 11 and possibly others) in the `java.util.ServiceLoader` implementation. I've filed a bug with Oracle.

**Comment by veita** [comment]
OK, I should not have blamed JDK.

The documentation of `java.util.ServiceLoader` clearly states that 

> Instances of this class are not safe for use by multiple concurrent threads.

**Comment by veita** [comment]
This bug seems to be fixed in 1.2.2.

**Comment by aloz77** [comment]
Nope, still experience this bug with 1.2.2. 

```
implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.2' 
implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

```
Revert to 1.2.0 as workaround.

**Comment by veita** [comment]
For me the following test failed with 1.2.1 but now works with 1.2.2

```java
public void testPahoClientMqtt572Fixed() throws Exception
{
	final CountDownLatch             l_latch;
	final AtomicReference<Exception> l_refEx;

	l_latch = new CountDownLatch(50);
	l_refEx = new AtomicReference<>();

	for (int i = 0; i < 500; i++)
	{
		new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				try
				{
					NetworkModuleService.validateURI("ssl://mqtt.example.org:8883");
				}
				catch (Exception l_e)
				{
					l_refEx.set(l_e);
				}
				finally
				{
					l_latch.countDown();
				}
			}
		}).start();
	}

	l_latch.await(20, TimeUnit.SECONDS);

	assertEquals(0, l_latch.getCount());
	assertNull("This bug should have been fixed in version 1.2.2.", l_refEx.get());
}
```

**Comment by aloz77** [comment]
Hmm, no idea, I'm still getting this error with 1.2.2. Looks like a race condition somewhere. The debug build seems to be less affected than prod build.

```
2019-11-19 09:04:30.965 28650-28650/? E/bs: MQTT Connect Failure due to java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://farmer.cloudmqtt.com:18075"
2019-11-19 09:04:30.965 28650-28650/? W/System.err: java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://farmer.cloudmqtt.com:18075"
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.a.a.i.<init>(MqttAsyncClient.java:454)
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.a.a.i.<init>(MqttAsyncClient.java:320)
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.android.service.e.a(MqttConnection.java:289)
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.android.service.MqttService.a(MqttService.java:329)
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.k(MqttAndroidClient.java:467)
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.a(MqttAndroidClient.java:76)
2019-11-19 09:04:30.966 28650-28650/? W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient$b.onServiceConnected(MqttAndroidClient.java:115)

```

**Comment by sp193** [comment]
This is just a stab in the dark, but should synchronized be added to createInstance() too?

**Comment by veita** [comment]
> This is just a stab in the dark, but should synchronized be added to createInstance() too?

That‘s true. To make things clear I would even synchronize on `FACTORY_SERVICE_LOADER` instead of `NetworkModuleService`.

**Comment by rladstaetter** [comment]
stumbled across this issue as well i think.

can confirm that with 1.2.0 it works with windows for me, 1.2.2 it does not.

interestingly, 1.2.2 works when started under osx.

used mosquitto under windows, moquette under mac if this makes any difference.

**Comment by ArikYa** [comment]
I had the same issue, always on release builds with 1.2.2. It turns out to be obfuscation issue, once I added this library to the proguard-rules file, all worked great

**Comment by Mi-La** [comment]
Also facing this with org.eclipse.paho.client.mqttv3-1.2.2.jar. Is it just a v3 problem? I cannot get working even a basic example :-(. It would be really nice to put some info here.

**Comment by davidevertuani** [comment]
> I had the same issue, always on release builds with 1.2.2. It turns out to be obfuscation issue, once I added this library to the proguard-rules file, all worked great

@ArikYa could you share your `proguard-rules.pro` lines that solve the issue? We tried adding `-keep` rules but that didn't work for us. Thanks!

**Comment by ashokv915** [comment]
Facing the same issue with  org.eclipse.paho.client.mqttv3-1.2.2.jar. When I downgraded to 1.2.0 its worked.

**Comment by ahavansky** [comment]
The problem is reproduced on version 1.2.2: 
`java.lang.IllegalArgumentException: no NetworkModule installed for scheme "ssl" of URI `

**Comment by rdasgupt** [comment]
@ahavansky 
Could you please try with the new MQTTv3 service release 1.2.4?

**Comment by sanyeMen** [comment]
> The problem is reproduced on version 1.2.2:
> `java.lang.IllegalArgumentException: no NetworkModule installed for scheme "ssl" of URI `

In version 1.2.4, the problem was resolved

**Comment by rdasgupt** [comment]
@sanyeMen 
Thanks for confirming. I am closing this issue. 
Please reopen if you see this problem again.

**Comment by bhavin2887** [comment]
<artifactId>**org.eclipse.paho.client.mqttv3**</artifactId>
I have tried 1.2.0, 1.2.2 and 1.2.4 but still facing the "no NetworkModule installed for scheme"tcp"" issue.

One more thing, I am able to run the program and things are working fine. But when I am creating a  jar file(service) then its showing above error.

Can anyone help what can be done here.

**Comment by aloz77** [comment]
I can confirm, that 1.2.4 still causes the exception in production builds. Should be reopened.

**Comment by jamshidrostami** [comment]
Try to add these lines to your `proguard-rules.pro` file

```
-keep class org.eclipse.paho.client.mqttv3.internal.* { *; }
-keep class org.eclipse.paho.client.mqttv3.spi.* { *; }
```

**Comment by v-zafari** [comment]
> 
> 
> Try to add these lines to your `proguard-rules.pro` file
> 
> ```
> -keep class org.eclipse.paho.client.mqttv3.internal.* { *; }
> -keep class org.eclipse.paho.client.mqttv3.spi.* { *; }
> ```
You save my life, thanks so much.

**Comment by aloz77** [comment]
Yes, lib 1.2.4 with those proguard rules seems to work :-)

**Comment by dmitrys** [comment]
On Android work fine in simple application but issue reproduced in application where a lot of threads. I think this ServiceLoader mechanism work no so good especially on Android.

**Comment by rladstaetter** [comment]
I can confirm 1.2.5 works with before-mentioned proguard rules. My problem was finally solved when I realised that our proguard rules eliminated certain files under META-INF/... which triggered 'no NetworkModule installed for scheme "tcp"' maybe useful for somebody else.

**Comment by sp193** [comment]
Since #714 was merged on 8th July and is part of the 1.2.5 milestone, does this problem still exist with 1.2.5? It might not have been part of the main 1.2.4 release, but its develop branch.

**Comment by Mustufa786** [comment]
I am getting this issue in 1.2.5 no NetworkModule installed for scheme "mqtt" of URI "mqtt://3.132.130.234:4040"
Can anybody pls help me to get rid of this problem?

**Comment by sp193** [comment]
There's no such protocol for this library. It's only either "tcp" or "ssl".

**Comment by vcsvetronind** [comment]
> > Try to add these lines to your `proguard-rules.pro` file
> > ```
> > -keep class org.eclipse.paho.client.mqttv3.internal.* { *; }
> > -keep class org.eclipse.paho.client.mqttv3.spi.* { *; }
> > ```
> 
> You save my life, thanks so much.
